## Importing raw data.
```{r setup}
library(tidyverse)
library(vroom)
library(here)
```

```{r}
user_1_info_file <- here("data-raw/mmash/user_1/user_info.csv")
user_1_info_data <- vroom(user_1_info_file)

# Read file into a tibble


# Finished function
user_1_info_data <- vroom(
  user_1_info_file,
  col_select = -1, # removes column named: 1
  col_types = cols(
    col_skip(), # copied from:  spec(user_1_info_data) - clarifies column types
    weight = col_double(),
    height = col_double(),
    age = col_double()
  ),
  .name_repair = snakecase::to_snake_case # converts to lower case letters
)
```

Before moving on to the exercise, run styler with with the Palette (Ctrl-Shift-P, then type “style file”), then add and commit the changes to the Git history through the RStudio Git interface with Ctrl-Shift-M or with the Palette (Ctrl-Shift-P, then type “commit”).

## Exercise: Import the saliva data.
```{r}
user_1_saliva_file <- here("data-raw/mmash/user_1/___")
user_1_saliva_data_prep <- vroom(
    user_1_saliva_file,
    col_select = ___,
    .name_repair = ___
)
___(user_1_saliva_data_prep)

user_1_saliva_data <- vroom(
    user_1_saliva_file,
    col_select = ___,
    col_types = ___,
    .name_repair = ___
)
```

